### ISSUE TITLE
My 5 coin

### ISSUE THREAD

**Issue by heretic13** [rust-compress/rc-zip#9]
I looked at your work. It seemed to me more convenient than crate "zip" (work on which is stopped). But I have a few comments.

1. The StoredEntry structure does not support **Clone**/**Copy** trait. If it supported, then it would be possible to save the received StoredEntry somewhere, to return to work with the archive later.

2. There are no examples.

3. Missing description of **get_reader** function in declaration
`pub fn reader<'a, F, R>(&' a self, get_reader: F) -> EntryReader <'a, R>
where
    R: Read,
    F: Fn(u64) -> R
`
I think this function gets an offset for **Read**, changes position and returns **Read**.
But not so simple.
3.1 **get_reader** returns an object, i.e. transfers ownership somewhere inside the library. You want to say that I have to make **Clone** to my **Read** object before giving it away? **std::fs::File** does not support cloning.
3.2. Let's look at another example. He is almost a worker, but still not.

```
fn open1 (archname: & dyn AsRef <Path>)
{
    let mut f = File :: open (archname) .unwrap ();
    let arch = parse_zip (& mut f);
    let entry = & arch.entries () [1];

    let rdr = entry.reader (| offset |
    {
        f.seek (std :: io :: SeekFrom :: Start (offset)). unwrap ();
        f
    });
}
```

Here f cannot be used because the closure type is **Fn**, although it would have to be **FnMut.**
`move | offset | {...}` also does not work

**Comment by fasterthanlime** [comment]
You can look at https://github.com/rust-compress/rc-zip/blob/master/samples/jean/src/main.rs for an example of correct usage. You'll notice it uses a Cursor.

The reason the API is designed this way is to let you extract multiple entries in parallel if you want to :)

`File` is not `Clone` because it refers to an operating system file descriptor, which has it's own position - concurrent reads would conflict!
